### ISSUE TITLE
Errors occur in MNIST experiment.

### ISSUE THREAD

**Issue by MKopt2019** [PdIPS/CBXpy#14]
Hello,

Thanks for the great implementations on CBO.

Since I'm new to CBO, I tried to run the MNIST experiment in Google Collab, but I got the following error message.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-723e6222c7ab>](https://localhost:8080/#) in <cell line: 118>()
    116 def norm_torch(x, axis, **kwargs):
    117     return torch.linalg.norm(x, dim=axis, **kwargs)
--> 118 noise = anisotropic_noise(norm = norm_torch, sampler = torch.normal)
    119 resamplings = [cbx.utils.resampling.loss_update_resampling(M=1, wait_thresh=40)]
    120 

TypeError: anisotropic_noise.__init__() got an unexpected keyword argument 'norm'

Could you please check the reason for this error?

Thanks again for this project.

M.K.

**Comment by TimRoith** [comment]
Hi, thanks for the interest, and sorry for the inconvenience. We are currently in a pre-publication phase for the project, that's why I did not update the version on PyPI (i.e. the one installed with pip) yet. The notebooks run on the current version of the repo, so to use it one would have to install the git version. As soon as we are ready, I'll update the version on PyPi and it'll work with this version. 

Best
Tim

**Comment by TimRoith** [comment]
Btw don't hold back to ask more questions, especially in the early phase of a project it is great to hear a lo of feedback.

Thanks
Tim

**Comment by MKopt2019** [comment]
Got it, thanks for the explanation. I really appreciate your efforts on this project!

Sincerely,
M.K.

**Comment by TimRoith** [comment]
Thank you very much for your question!

Best
Tim
